### ISSUE TITLE
Hard-coded filename(s) prevent "document-tests.sh" from running

### ISSUE THREAD

**Issue by KurtPfeifle** [istopwg/ippeveselfcert#1]
* When I run *"document-tests.sh"*, it complains about missing PWG Raster sample files and asks to download them from  [ftp.pwg.org/pub/pwg/ipp/examples/](http://ftp.pwg.org/pub/pwg/ipp/examples/) . That's ok, but then...

* ...looking at that location, I see different versions: there are ones from 2011, and newer ones from 2015. Which one(s) to use?

* The *"document-tests.sh"* script itself has hard-coded a test for the "2011"-versions and bails out if only "2015"-versions are available. 

* Also, the associated *"documents-tests.test"* file also contains the "2011" version names hard-coded.... 

* Finally, it is not clear if one should download the PWG raster samples for *ALL* resolutions (I guess the resolutions reported by the IPP printer to be supported should suffice?).  To clarify that in the message printed to the user when the test fails would be helpful.

In lieu of a suitable IPP printer in my current environment I resorted to test against a locally installed CUPS-1.7.5 queue (knowing it is not supposed to pass most of the tests, but wanting to see in general how this testing would work). This is when I noticed the problem with the  hard-coded versions, plus the following:

~~~
"document-tests.test":
    D-1. PWG Raster Format Tests (mandatory)                             [PASS]
ipptool: Filename "pwg-raster-samples-${RASTER_RESOLUTION}-20111130/black-1/color.jpg-4x6-black-1-600dpi.pwg" on line 68 cannot be read.
ipptool: Filename mapped to "pwg-raster-samples-1200dpi-20111130/black-1/color.jpg-4x6-black-1-600dpi.pwg".
~~~

That "line 68" is from "document-tests.test". It reads:

~~~
   FILE pwg-raster-samples-${RASTER_RESOLUTION}-20111130/black-1/color.jpg-4x6-black-1-600dpi.pwg
~~~

I'm not sure why the var ${RASTER_RESOLUTION} did not resolve in the output line? And why it seems to be "mapped to 1200dpi"? And why is the "600dpi.pwg" file suffix hard-coded throughout the *"document-tests.test"* file?

----
*(Note, I've not run this on one of the required/recommended OS platforms, but on Debian Jessie.)*

**Comment by michaelrsweet** [comment]
OK, just pushed a fix for this issue. Tested end-to-end with different ippserver settings to make sure things were working reliably...

Please stick with the sample files from 20150616 since the older files contains errors.
