### ISSUE TITLE
ipptool / ippfind and others not latest in istopwg/ippsample project

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#10]
This project doesn't have the latest stable revisions of ipptool and ippfind, which will resolve some problems with current sources that affect pending test updates (e.g. issue reported in https://github.com/istopwg/ippsample/issues/2)

**Comment by michaelrsweet** [comment]
[master 1dbd639] Sync with CUPS 2.2 upstream (master)
