### ISSUE TITLE
Changes needed to support print servers

### ISSUE THREAD

**Issue by michaelrsweet** [istopwg/ippeveselfcert#11]
Need to update test suite and/or submission page to better support IPP Everywhere print servers, particularly for virtual print servers that have no associated hardware marking devices (e.g. process and send PDF file over some transport) and thus do not have supplies, media, or printer identification.

**Comment by michaelrsweet** [comment]
The only tests in the 1.0 suite that do not apply to virtual and release print servers are I-9 (printer-supply/-description/-info-uri) and I-27 (media-needed).

This bug will track addition of a "Test results are for a print server or virtual printer" checkbox to the submission portal so that those specific test failures can be whitelisted.

**Comment by wifiprintguy** [comment]
Should this be resolved in a 1.0 Update 1 or a 1.1 release?

**Comment by michaelrsweet** [comment]
This doesn't involve the tools, just the web site. My plan is to get the changes on the submission portal soon...

**Comment by michaelrsweet** [comment]
[master fefbf8f] Issue 11: Support print servers.

**Comment by michaelrsweet** [comment]
Pending review and testing, this should now be fixed on www.pwg.org.
