### ISSUE TITLE
ipp-tests.test: update all EXPECTS testing for type dateTime to also allow "unknown" and some also support "no-value"

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#13]
See thread here: http://www.pwg.org/pipermail/ipp/2016/018995.html

Original message was this:

"While running the IPP Everywhere Self Certification suite against a printer that has no persistent clock, we saw several failures having to do with the state of some time related attributes. When I started digging into those attributes, I discovered that some attributes, such as "date-time-at-processing" or "date-time-at-completed", are defined as (dateTime | no-value) while others such as "date-time-at-creation" or "printer-current-time" are simply defined to be of type "dateTime". And yet the description of "printer-current-time" in even the latest draft of RFC 2911bis allowed the attribute to have the out-of-band value 'no-value'.

What is the right thing to do in these cases? And should it be acceptable if a Printer that lacks a clock reports 'no-value' for "printer-config-change-date-time"? If it is OK to return 'no-value' then I think tests I-9 and I-14 may need to be fixed."

IPP WG minutes (http://ftp.pwg.org/pub/pwg/ipp/minutes/ippv2-concall-minutes-20161005.pdf) gave this guidance for updating the IPP Everywhere Self Certification test suite:

⁃ Allow both no-value and unknown for date-time-at-xxx and
printer-current-time and printer-config-change-date-time and
printer-state-change-date-time

**Comment by michaelrsweet** [comment]
[master d3ed928] Remove SVN Id keywords from test files.

**Comment by wifiprintguy** [comment]
In your fixes, there are 5 lines like so:

EXPECT date-time-at-creation OF-TYPE dateTime|unknown IN-GROUP job-attributes-tag COUNT 1

I think it should also support "no-value" to grandfather in the value as we discussed, like so:

EXPECT date-time-at-creation OF-TYPE dateTime|no-value|unknown IN-GROUP job-attributes-tag COUNT 1

**Comment by michaelrsweet** [comment]
Based on our discussions, copying a 'no-value' from "printer-current-time" is considered deprecated behavior (with a corresponding note in RFC2911bis).

RFC 2911 defines "date-time-at-creation" with a dateTime syntax, while "date-time-at-processing" and "date-time-at-completed" have a dateTime|no-value syntax. The proposed AUTH-48 changes in RFC2911bis will add unknown values to all three "date-time-at-xxx" attributes but will not add the no-value syntax to "date-time-at-creation". (or at least that is what I have in the minutes)

Unless this actually causes a problem with a shipping product, I'd like to keep this as-is; we can always whitelist this failure in the submission portal...

**Comment by wifiprintguy** [comment]
This problem is the sole problem preventing some shipping HP products from passing the tests - that is how I became aware of the situation in the first place. These changes won't allow the I thought from our discussions on that call that we should be grandfathering in the deprecated behavior insofar as it should not prevent the tests from passing. I don't think it is really good to continue the practice of implementing these deprecations via the self cert submission web form parsing logic because it isn't clear to the testers whether they should submit if the tests themselves indicate a failure.

I can share portions of this thread over to the reflector to have it discussed there.

**Comment by michaelrsweet** [comment]
Well, if we have shipping products that need this then I'll go ahead and make the change. Reopening so we can address for update 1...

**Comment by wifiprintguy** [comment]
I just re-ran the tests, and the lines that test "printer-config-change-date-time" and "printer-state-change-date-time" are also a problem for us:

    I-9. Get-Printer-Attributes Operation (default)                      [FAIL]
        RECEIVED: 12588 bytes in response
        status-code = successful-ok (successful-ok)
        EXPECTED: printer-config-change-date-time OF-TYPE dateTime (got no-value)
        EXPECTED: printer-state-change-date-time OF-TYPE dateTime (got no-value)

**Comment by michaelrsweet** [comment]
I updated the tests to accept no-value or unknown for these attributes in the last commit. Please make sure you have pulled the latest stuff...

**Comment by michaelrsweet** [comment]
New fix confirmed via email...
