### ISSUE TITLE
ipp-tests.test : I-27 Test - 10 second delay is sometimes inadequate

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#18]
On line 1112, at the start of Test I-27, there is the directive:
    "DELAY 10"

There are some printers that have a longer than 10 second delay before reporting 'media-needed'. Suggest leaving the "DELAY 10" but adding a retry to the EXPECT statement on line 1125 so that it becomes:

	EXPECT printer-state-reasons OF-TYPE keyword IN-GROUP printer-attributes-tag WITH-VALUE "/^media-needed/" REPEAT-NO-MATCH REPEAT-LIMIT 12

This puts an upper bounds on the wait but will list the retries. Polling is not desirable but is inevitable here. (IPP Eventing? Let's not go there here...) We could do DELAY 5 and double the REPEAT-LIMIT so that the polling frequency is 5 seconds.

**Comment by michaelrsweet** [comment]
This was fixed by pull request #19.
