### ISSUE TITLE
document test cannot run

### ISSUE THREAD

**Issue by jiape** [istopwg/ippeveselfcert#30]
1. git clone the latest test suite.
2. cd tests
3. curl http://ftp.pwg.org/pub/pwg/ipp/examples/pwg-raster-samples-300dpi-20150616.zip >temp.zip
4. rm temp.zip
5. cd ..
6. ./runtests.sh document-tests.sh "Example Test Printer"

Actual Results:
You must first download and extract the PWG Raster Format sample files from:

    http://ftp.pwg.org/pub/pwg/ipp/examples/

Before you can run this script.

(Look for the @PWGRASTER_VERSION@ files...)

**Comment by michaelrsweet** [comment]
@jiape I cannot reproduce from a fresh checkout - are you running the configure script and making things after you clone the repository?

Also, are you unzipping the sample file archive?

**Comment by jiape** [comment]
yes, i run configure && make after cloned the scripts, i can run bonjour-tests, ipp-tests.

yes I unzipped the sample file followed README.

**Comment by michaelrsweet** [comment]
[master 523e102] Remove old PWGRASTER_VERSION in document-tests.sh (Issue #30)

**Comment by jiape** [comment]
Thanks Michael, 
it works now.
