### ISSUE TITLE
Some bonjour tests failed on Ubuntu, but passed on macOS, same version of tests on same printer

### ISSUE THREAD

**Issue by jiape** [istopwg/ippeveselfcert#31]
Ubuntu Results:
B-1. IPP Browse test: FAIL
B-2. IPP TXT keys test: FAIL
B-3. IPP Resolve test: FAIL
B-4. IPP TXT values test: FAIL
   pdl is missing image/jpeg: 'application/PCLm,application/octet-stream,image/pwg-raster,image/urf'
"bonjour-value-tests.test":
    Validate TXT record values using Get-Printer-Attributes              [PASS]
B-5. TLS tests: SKIP
B-5.1 HTTP Upgrade test: SKIP
B-5.2 IPPS Browse test: SKIP
B-5.3 IPPS TXT keys test: SKIP
B-5.4 IPPS Resolve test: SKIP
B-5.5 IPPS TXT values test: SKIP
Summary: 10 tests, 0 passed, 4 failed, 6 skipped
Score: 60%

macOS Results:
B-1. IPP Browse test: FAIL
B-2. IPP TXT keys test: PASS
B-3. IPP Resolve test: PASS
B-4. IPP TXT values test: FAIL
   pdl is missing image/jpeg: 'application/PCLm,application/octet-stream,image/pwg-raster,image/urf'
"bonjour-value-tests.test":
    Validate TXT record values using Get-Printer-Attributes              [PASS]
B-5. TLS tests: PASS
B-5.1 HTTP Upgrade test: PASS
B-5.2 IPPS Browse test: FAIL
B-5.3 IPPS TXT keys test: PASS
B-5.4 IPPS Resolve test: PASS
B-5.5 IPPS TXT values test: FAIL
   pdl is missing image/jpeg: 'application/PCLm,application/octet-stream,image/pwg-raster,image/urf'
"bonjour-value-tests.test":
    Validate TXT record values using Get-Printer-Attributes              [PASS]
Summary: 10 tests, 6 passed, 4 failed, 0 skipped
Score: 60%

**Comment by michaelrsweet** [comment]
@jiape What version of Ubuntu are you using?

Also, is this with the published tools or from the current Git repository?

**Comment by jiape** [comment]
Here is my Ubuntu version:
Welcome to Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-128-generic x86_64)

from the current git repository.

**Comment by michaelrsweet** [comment]
This looks like your Ubuntu system is missing the libgnutls-dev package, which is required to do TLS testing...
