### ISSUE TITLE
ipp-tests.test.in : Basic printing tests  should use PWG Raster rather than JPEG

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#33]
The "ipp-tests.test" / "ipp-tests.test.in" files include a number of tests that test printing using JPEG files. This is now not acceptable because with IPP Everywhere 1.1 Printers are now only required to support JPEG if they are color printers. This should be refactored to use a PWG Raster file of the appropriate resolution.

**Comment by michaelrsweet** [comment]
[master 6891fa7] IPP tests need to use PWG Raster files, not JPEG (Issue #33)
