### ISSUE TITLE
"I-9. Get-Printer-Attributes Operation (default)" failed due to expected "image/jpeg"

### ISSUE THREAD

**Issue by jiape** [istopwg/ippeveselfcert#37]
"image/jpeg" is optional for mono printer in ipp everywhere version 1.1

**ipp-tests.sh**
EXPECT document-format-supported OF-TYPE mimeMediaType IN-GROUP printer-attributes-tag WITH-VALUE "image/jpeg"

**Comment by michaelrsweet** [comment]
This is already addressed in master...
