### ISSUE TITLE
D-2. JPEG Tests (mandatory) in "document-test.sh"

### ISSUE THREAD

**Issue by jiape** [istopwg/ippeveselfcert#38]
"image/jpeg" is optional for mono printer in ipp everywhere v1.1
    
D-2. JPEG Tests (mandatory)                                          [FAIL]
        RECEIVED: 7876 bytes in response
        status-code = successful-ok (successful-ok)
        EXPECTED: document-format-supported WITH-VALUE "image/jpeg"
        GOT: document-format-supported="application/PCLm"
        GOT: document-format-supported="application/octet-stream"
        GOT: document-format-supported="image/pwg-raster"
        GOT: document-format-supported="image/urf"
    D-2.1 Print color.jpg with defaults                                  [FAIL]

**Comment by michaelrsweet** [comment]
[master 61b27f4] Make JPEG tests conditional (Issue #38)
