### ISSUE TITLE
"You must first download and extract the PWG Raster...." shows up after followed README to setup document tests

### ISSUE THREAD

**Issue by jiape** [istopwg/ippeveselfcert#39]
You must first download and extract the PWG Raster Format sample files from:

    http://ftp.pwg.org/pub/pwg/ipp/examples/

Before you can run this script.

**README:**
The corresponding PWG Raster sample files (see link in the introduction) MUST be placed in a subdirectory of the "tests" directory. For example:

cd tests
curl http://ftp.pwg.org/pub/pwg/ipp/examples/pwg-raster-samples-300dpi-20150616.zip >temp.zip
unzip temp.zip
rm temp.zip
cd ..

**Comment by wifiprintguy** [comment]
Previously (IPP Everywhere 1.0) when image/jpeg was required for all printers, using a JPEG image in ipp-tests.test was the easiest way to handle it. With IPP Everywhere 1.1 we might need to implement some level of automation. But the tester will need to acquire the various resolutions their printer supports for the document-tests.sh / document-tests.bat testing anyway.

**Comment by michaelrsweet** [comment]
The README in the tests directory already has these instructions. I've updated them for 1.1...
