### ISSUE TITLE
Windows IPP Everywhere Self Cert 1.0 Update 3: ipptool fails to run - missing regex.dll

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#41]
If you install the IPP Everywhere Self Certification 1.0 Update 3 for Windows on a Windows 10 system (https://ftp.pwg.org/pub/pwg/tools/sw-ippeveselfcert10-20181023-windows.msi), and run "c:\Program Files\IPP Everywhere v1.0 Printer Self-Certification Tools\ipptool.exe", a dialog appears saying "The code execution cannot proceed because regex.dll was not found. Reinstalling the program may fix this problem."

**Comment by michaelrsweet** [comment]
Will look into this; normally the project output should have been included in the installer and I didn't have any problems when I tested in an isolated VM...

**Comment by michaelrsweet** [comment]
Update 4 in testing with this fix...
