### ISSUE TITLE
Test for finishings support should define HAVE_FINISHINGS if "finishings-supported" has value other than 3 (none)

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#47]
This line:

https://github.com/istopwg/ippeveselfcert/blob/b382cc129d055a9ac3aa949ebaf9a85563c732ea/tests/ipp-tests.test#L369

Should say instead:

`EXPECT finishings-supported OF-TYPE enum IN-GROUP printer-attributes-tag WITH-VALUE >3 DEFINE-MATCH HAVE_FINISHINGS`

This way it will only define HAVE_FINISHINGS if "finishings-supported" contains a value other than 3 (none).

**Comment by michaelrsweet** [comment]
[master e73039f] Only define HAVE_FINISHINGS if finishings-supported has a value other than '3' (none). (Issue #47)
