### ISSUE TITLE
HAVE_IDENTIFY_PRINTER isn't defined prior to test I-9 that uses it

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#48]
https://github.com/istopwg/ippeveselfcert/blob/b382cc129d055a9ac3aa949ebaf9a85563c732ea/tests/ipp-tests.test#L166

Because HAVE_IDENTIFY_PRINTER isn't defined until I-10, add a new I-9.1 to check for Identify-Printer support, and then make the existing I-9 be I-9.2. That way, Identify-Printer will be tested.

**Comment by michaelrsweet** [comment]
[master c89f7a0] Define HAVE_IDENTIFY_PRINTER in test I-6 (first successful Get-Printer-Attributes) so that test I-9 runs (Issue #48)
