### ISSUE TITLE
Some printer description attributes are required in the job template attributes

### ISSUE THREAD

**Issue by Dingyuguan** [istopwg/ippeveselfcert#52]
ipp-tests.bat "XXX-XXXX-0198D4"
I-10.6. Get-Printer-Attributes Operation (job-template)              [FAIL]
        RECEIVED: 4355 bytes in response
        status-code = successful-ok (successful-ok)
        EXPECTED: media-bottom-margin-supported
        EXPECTED: media-col-supported
        EXPECTED: media-left-margin-supported
        EXPECTED: media-right-margin-supported
        EXPECTED: media-size-supported
        EXPECTED: media-source-supported
        EXPECTED: media-top-margin-supported
        EXPECTED: media-type-supported

In Table5 of IPP Everywhere v1.1, above expected attributes are defined as printer description attributes, not job template attributes. But this test item requies these attributes in job-template. Is it right?

**Comment by michaelrsweet** [comment]
Per STD 92, the "job-template" group includes all Printer Description/Status attributes providing values for Job Template attributes:

> For Printers, the possible names of attribute groups are:
>
> -  'job-template': the subset of the Job Template attributes that apply to a Printer (the last two columns of Table 8 in [Section 5.2](https://tools.ietf.org/html/rfc8011#section-5.2)) that the implementation supports for Printers.

All of the "media-xxx-supported" attributes provide the supported values for the "media-col" Job Template attribute, thus they are required to be returned as part of the 'job-template' group.

**Comment by Dingyuguan** [comment]
Thank you for your reply.
