### ISSUE TITLE
IPP Everywhere v1.1 ipp-tests.sh fails device for finishing-template-support name(MAX) value

### ISSUE THREAD

**Issue by crizzo-xerox** [istopwg/ippeveselfcert#59]
From PWG 5100.1 IPP Finishings 2.1
 
finishing-template (type2 keyword | name(MAX))
finishing-template-supported (1setOf (name(MAX) | type2 keyword))
 
`    I-10. Get-Printer-Attributes Operation (default)                     [FAIL]
        RECEIVED: 17237 bytes in response
        status-code = successful-ok (successful-ok)
        EXPECTED: finishing-template-supported OF-TYPE keyword (got nameWithoutLanguage)
        EXPECTED: finishing-template-supported WITH-VALUE "none"
        GOT: finishing-template-supported="jog-offset"`
 
Doesn't the spec allow name(MAX) aka nameWithoutLanguage?

Also, is "none" value required since the following wording in the IPP Finishings 2.1 spec implies "Except for 'none'":

6.8 finishing-template-supported (1setOf (name(MAX) | type2 keyword))
The "finishing-template-supported" Printer attribute lists the supported values for the "finishing-template" (section 5.2.1) member. Except for 'none', Printers MUST list all "finishings-supported" keyword value equivalents in the list of "finishing-template-supported" values.

Thanks

**Comment by michaelrsweet** [comment]
[master 295cc2b] Allow 'name' values for "finishing-template-supported" (Issue #59)
