### ISSUE TITLE
IPP Everywhere v1.1 ipp-test.sh test I-10.3 fails printer for successful-ok-ignored-or-substituted-attributes response

### ISSUE THREAD

**Issue by crizzo-xerox** [istopwg/ippeveselfcert#60]
Test sends Get-Printer-Attributes operation request for requested-attributes = 'none'.  Since this is an unsupported attribute, a compliant printer can return IPP status of successful-ok-ignored-or-substituted-attributes, with request-attributes as supported, but with value none not supported.  This response should not be treated as a failure.

**Comment by michaelrsweet** [comment]
[master 39383d6] Allow Get-Printer-Attributes to soft-fail (Issue #60)
