### ISSUE TITLE
IPP Everywhere v1.1 ipp-tests.sh reports failure for blank value for printer-alert and printer-alert-description when no alerts present

### ISSUE THREAD

**Issue by crizzo-xerox** [istopwg/ippeveselfcert#61]
A blank string for printer-alert and printer-alert-description should be acceptable response when no alerts are present at the printer.  This also corresponds to errata issue added for PWG 5100.9 sections 5.2 and 5.3.  Test should also accept legacy values for 'code=other' reported by some implementations when no alert is present.

**Comment by michaelrsweet** [comment]
[master 38d4937] Fix empty printer-alert values (Issue #61)
