### ISSUE TITLE
Add options to allow the IPP Everywhere Self-Certification tool set to be run non-interactively

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#62]
If the IPP Everywhere Self-Certification tools can be run in a "non-interactive batch mode" then the tests could be run by continuous integration systems. This would help to enable their incorporation into printer firmware development systems. That type of system integration could, in turn, drive further printer adoption, delivering on the IPP Everywhere value proposition.

**Comment by wifiprintguy** [comment]
Any tests that require human interaction should be skipped. What about tests that cause the printer to produce output? Should that be a "level 2 non-interaction"?

**Comment by michaelrsweet** [comment]
I think we need to split "no print" functionality out as a separate option.

That said, while there is certainly some value in verifying that the required attributes and values are reported, removing printing from the tests removes at least half of the tests... :)

**Comment by michaelrsweet** [comment]
[master a366dd4] Add "make test" target and "buildtest.sh" script (Issue #56, Issue #62)

Set the `IPP_EVERYWHERE_SERVER` environment variable to omit the media-needed test. If you just want to do the basic IPP tests then use the "runtests.sh" script.
