### ISSUE TITLE
"Close-Job" should be 0x003A and "Resubmit-Job" should be 0x003B

### ISSUE THREAD

**Issue by syoungatcda** [istopwg/ippeveselfcert#63]
The code for "Close-Job" operation should be 0x003A and "Resubmit-Job" should be 0x003B, instead of "Close-Job"=0x003B and "Resubmit-Job"=0x003A defined in cups\cups\ipp-support.c
https://github.com/apple/cups/blob/master/cups/ipp-support.c#L205

**Comment by michaelrsweet** [comment]
After further research, the original definitions in JPS2 were listed out-of-order. The correct value is 0x003B for Close-Job and 0x003A for Resubmit-Job, which is what CUPS and ippeveselfcert expect.
