### ISSUE TITLE
Lexmark 1.1 update 2 feedback: Document Format Tests

### ISSUE THREAD

**Issue by michaelrsweet** [istopwg/ippeveselfcert#66]
[Reported via IPP mailing list]

It appears that the tool blasts down as many print files as the printer will accept.   On a slower color printer, which takes quite a while to print the jobs, the test script times out while the jobs are still printing.  We manually added some delays in the test script which seemed to resolve the problem.   Ideally, the test should query for "job completed" before sending the next job.  I would also be nice to see the test prompt to load the correct paper size in the tray whenever the job uses paper sizes that are different from Letter/A4.

**Comment by wifiprintguy** [comment]
I think this should be broken into two distinct issues:

1. Adjusting the testing algorithm in "document-tests.test" to repeat until the "job-state" is in a terminal state or a VERY long timeout is reached (to allow Issue #62 to complete even if there is some failure in an automated / non-attended execution of the tests).

2. Adding a test (IMHO to "ipp-tests.test") that exercises a media mismatch causing the printer to stop processing / prevent processing until the requested media is loaded.

**Comment by michaelrsweet** [comment]
@wifiprintguy The ipp-tests already end with the media-needed test (remove media, print a file), and the document tests are supposed to test just printing and not other aspects of IPP conformance. *Adding* a test would require an update of the self-certification manual...

**Comment by wifiprintguy** [comment]
As we discussed today at the PWG February 2021 F2F, a possible solution for Issue #68 might also provide a solution for this issue's need for flow control by providing a way to pause the test until the Job or Printer has reached a particular status.

**Comment by michaelrsweet** [comment]
[master 390be9d] Wait for jobs to complete before proceeding (Issue #66)
