### ISSUE TITLE
ippevesubmit doesn't seem to be detecting finishing options

### ISSUE THREAD

**Issue by michaelrsweet** [istopwg/ippeveselfcert#67]
A printer that reports many finishing options is not recording those options in the generated JSON file when ippevesubmit is run. Need to determine why...

**Comment by michaelrsweet** [comment]
OK, it looks like the program is looking at the 9th of the IPP tests (I-9: Identify-Printer Operation) instead of the 10th test (I-10: Get-Printer-Attributes Operation (default)).

**Comment by jacobsb** [comment]
Hi Michael,
Is there is a target date for this issue?  I have some finishing products that I would like to complete testing on soon.  Thanks!

**Comment by michaelrsweet** [comment]
@jacobsb I just need to schedule some time for this. The actual fix is extremely simple so once I have a full day to devote to the build/test cycle I'll be able to get a beta out quickly.

**Comment by michaelrsweet** [comment]
[master faffcf9] Fix reporting of finishing features by `ippevesubmit` (Issue #67)
