### ISSUE TITLE
bonjour-tests.sh: Requiring the best practice resource path "ipp/print" causes print servers to fail

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#7]
If one runs the "bonjour-tests.sh" script against an IPP Everywhere Printer object hosted by a CUPS print server, it will fail because the resource path is not the best-practice "ipp/print" resource path.  IPP Everywhere doesn't require that the printer's resource path is "ipp/print" so this should be removed from the test, to allow servers to pass.  If there is a required resource path mandated in updates to IPP Everywhere this can be re-added.

**Comment by michaelrsweet** [comment]
Feel free to push your change to master...
