### ISSUE TITLE
ippevesubmit wasn’t updated

### ISSUE THREAD

**Issue by michaelrsweet** [istopwg/ippeveselfcert#71]
The ippevesubmit program wasn't updated for the changes to the document format tests, so the total number of tests has changed to 65.

**Comment by wifiprintguy** [comment]
As @michaelrsweet said in an email reply, please add "--override" when you run ippevesubmit to bypass this check while we are working to get 1.1 Update 4 built and posted.

**Comment by michaelrsweet** [comment]
[master 4444f10] Fix document format test count (Issue #71)
