### ISSUE TITLE
Issue that B-5. TLS tests have been skipped using Self Certification 1.1 Tools - Update 3

### ISSUE THREAD

**Issue by taikiarai** [istopwg/ippeveselfcert#72]
Hi,

As for the Self Certification 1.1 Update 3, our engineer have found an issue below.
This issue can be reproduced not only on OKI printer but also on Lexmark one. Please find the attached files.
[Test Result.zip](https://github.com/istopwg/ippeveselfcert/files/7119354/Test.Result.zip)

I'm not sure the tool includes this issue or our Win10 test envirnment has some problems to cause this issue.
It would be so helpful if you investigate it.

Please let me know if you have any questions.
Thank you. Cheers.

[Issue]
OKI printer supports TLS 1.2 now, but B-5. TLS tests have been skipped due to the command argument in red below using both command prompt and power shell for Win10. It seems that this argument has been implemented by Update 3.

Our engineer also has reported me that TLS tests have been completely executed and everything goes well If the argument has been changed --txt-TLS '^[1-9].[0-9]' to --txt-TLS 1.2.

https://ftp.pwg.org/pub/pwg/tools/sw-ippeveselfcert11-20210517-windows.msi (0210517_dnssd-tests.bat)
:: B-5. TLS tests: Performed only if TLS is supported
set result=SKIP
ippfind "%name%._ipp._tcp.local." --txt-TLS '^[1-9].[0-9]' --quiet && set result=PASS
if "%result%" == "PASS" (
       set /a pass+=1
       set HAVE_TLS=1
) else (
       set /a skip+=1
       set HAVE_TLS=0
)

**Comment by michaelrsweet** [comment]
This appears to work correctly for me now with the 1.1 update 4 tools. Please let me know how they work for you.

**Comment by taikiarai** [comment]
Hi Michael,

It works correctly with v1.1 Update4(Beta) as our engineer has reported to me. Please close this issue.
Many thanks of this. Cheers.

**Comment by taikiarai** [comment]
Or do I need to close this?

**Comment by michaelrsweet** [comment]
@taikiarai no I can do it, thank for you confirming!
