### ISSUE TITLE
Create 1200dpi test files

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#74]
HP has some printers that support 1200dpi PWG Raster, but the PWG doesn't have 1200dpi files available (at least not listed on the IPP Everywhere Self-Certification page - https://www.pwg.org/ippeveselfcert/index.html). Add 1200dpi files.

**Comment by wifiprintguy** [comment]
The script produces files with a small change to the naming convention: the files produced by the script embeds the colorspace keywords in the name (e.g. "pwg-raster-samples-300dpi/srgb_8/onepage-letter-srgb_8-300dpi.pwg"), whereas the existing files use colorspace substrings that look like the keywords but have some characters that are different from those in the keywords (e.g. "./pwg-raster-samples-300dpi/srgb-8/onepage-letter-srgb-8-300dpi.pwg") which means that the document-tests.test has to have many duplicate tests. However, this naming convention change will likely cause the tools themselves to be broken. I'll file a separate issue to propose we update the .test files to use the new naming convention and we can discuss that there.

**Comment by michaelrsweet** [comment]
@wifiprintguy There is already a script for this in the "scripts" directory called "make-pwg-samples.sh" :)

**Comment by wifiprintguy** [comment]
@michaelrsweet I didn't look in istopwg/ippsample but I should have. Oh, well - my bad! I'll file the naming convention change issue over there.
