### ISSUE TITLE
Add "54x86mm", "89x119mm", and "100mmx148mm" to IPP Everywhere Printer Self-Certification Tools

### ISSUE THREAD

**Issue by syoungatcda** [istopwg/ippeveselfcert#78]
Condition:
IPP Everywhere Printer Self-Certification Tools v1.1 Update 3

Our compact photo printers "SELPHY" support POST(148mmx100mm), L(89x119mm) and Card(54mmx86mm) sizes. 

They have already been Mopria certified since 2017:
•	Worldwide sales is 500,000 in 2021 (120,000 for North America & 220,000 for Europe)
•	Worldwide sales would be 640,000 in 2022 (110,000 for North America & 380,000 for Europe)

We have registered these media sizes to IANA:
https://www.iana.org/assignments/ipp-registrations/ipp-registrations.xml

media     om_card_54x86mm                 type2 keyword | name(MAX)     size name     [CANON20180329]
media     om_dsc-photo_89x119mm     type2 keyword | name(MAX)     size name     [CANON20180329]

Please add these media sizes to IPP Everywhere Printer Self-Certification Tools so our SELPHY printer can pass the test.

**Comment by michaelrsweet** [comment]
@syoungatcda Those sizes shouldn't prevent the printer from passing the self-certification tests - the names are well-formed and that is all the IPP tests care about.

Can you provide a sample of the error message that you are getting when you run the tools?

**Comment by syoungatcda** [comment]
@michaelrsweet 

We have retested and have the following test result.  Please see attached for the test log.

Environment:
SW version: sw-ippeveselfcert11-20210517-macos.zip
Device/OS: mac11.6.1(macMini)
Printer/Network: SELPHY(under development)/Wireless & Wired
[IPPTEST220201.txt](https://github.com/istopwg/ippeveselfcert/files/7981377/IPPTEST220201.txt)

Steps to Reproduce:
1. Download the lateset tools from https://istopwg.github.io/ippeveselfcert/
2. Extract "sw-ippeveselfcert11-20210517-macos.zip"
3. Go to ToolnoPWG Raster Files
4. Launch Terminal.app and run .\document-tests.sh "Canon SELPHY CPxxxx"

Expected Result:
User should run IPP Everywhre self certification tests w/ SELPHY

Acutal Result:
User is unable to run IPP Everywhre self certification tests w/ SELPHY
See the log "IPPTEST220201.txt"

**Comment by syoungatcda** [comment]
Sorry, I have closed it by accident.

Reopen the issue.  Please find below the test log:

--- dnssd-tests.sh "Canon SELPHY CPxxxx" ---
B-1. IPP Browse test: FAIL
B-2. IPP TXT keys test: PASS
B-3. IPP Resolve test: PASS
B-4. IPP TXT values test: ipp://CPxxxxc4a1c8.local:631/ipp/print
PASS
B-5. TLS tests: PASS
B-5.1 HTTP Upgrade test: PASS
B-5.2 IPPS Browse test: FAIL
B-5.3 IPPS TXT keys test: PASS
B-5.4 IPPS Resolve test: PASS
B-5.5 IPPS TXT values test: ipp://CPxxxxc4a1c8.local:631/ipp/print
PASS
Summary: 10 tests, 8 passed, 2 failed, 0 skipped
Score: 80%
--------------------------------------------------------------------

---ipp-tests.sh "Canon SELPHY CP1xxxx"---
Canon SELPHY CPxxxx IPP Results.plist: Cannot parse a NULL or zero-length data
-------------------------------------------------------------

---document-tests.sh "Canon SELPHY CPxxxx"---
You must first download and extract the PWG Raster Format sample files from:
    http://ftp.pwg.org/pub/pwg/ipp/examples/
Before you can run this script.
-----------------------------------------------------------------------

**Comment by wifiprintguy** [comment]
Hi @syoungatcda, those results indicate several things to me:

* dnssd-tests.sh: Your printer is most likely not advertising the IPP Everywhere mandated "_print" subtype for the "_ipp._tcp" and "_ipps._tcp" service types.

* ipp-tests.sh: Not sure what is going on here but something catastrophic occurred that prevented the test from running...more in a minute.

* document-tests.sh: Follow the instructions to download the correct PWG Raster files from that directory on the FTP site.

The IPP Everywhere Self-Certification 1.1 Update 3 zip file ought to provide copies of both ipptool and ippfind. What is the output of "ippfind"? And what is the output from running "ipptool -vt '<<IPP-URI-OF-SELPHY>>' ipp-tests.test?

**Comment by syoungatcda** [comment]
Hi, @wifiprintguy 

The following are what we have tested and the requests we have:

1. dnssd-tests.sh
- It has run correctly.
- We will consider how we support fail test cases in our printers.
2. ipp-tests.sh
- Unable to run test tool w/ipp-tests.sh. Could you investigate the cause?
- Able to run by entering ipptool -vt ipp://192.168.0.2:631/ipp/print ipp-tests.test"/Users/test/Desktop/sw-ippeveselfcert11-20210517/ipp-tests.test“  from Terminal.app. Please see the attached log file "IPPtest_.docx".
- We haven’t supported IPP Everywhere as “ipp-features-supported” attribute and other items, so it returns [FAIL] as Get-Printer-Attributes Operation (default). We will implement them for our printers.
3. document-tests.sh
- Unable to run test tool document-tests.sh though we have extracted and put PWG Raster Format sample files in. Could you investigate the cause?
- Able to run by entering ipptool -vt ipp://192.168.0.2:631/ipp/print document-tests.test"/Users/test/Desktop/sw-ippeveselfcert11-20210517/document-tests.test“  from Terminal.app. Please see attached log file "Doctest_.docx".
- Could you support media sizes as jpn_hagaki_100x148mm,om_dsc-photo_89x119mm,om_card_54x86mm in cert tools? The tool seems to require printers to print with na_letter_8.5x11in but SELPHY doesn’t return this media size in Get-Printer-Attributes (because SELPHY doesn't support letter size).

[IPPtest_.docx](https://github.com/istopwg/ippeveselfcert/files/7999330/IPPtest_.docx)

[Doctest_.docx](https://github.com/istopwg/ippeveselfcert/files/7999328/Doctest_.docx)

**Comment by wifiprintguy** [comment]
@syoungatcda The issues identified in test I-10 in IPPtest_.docx are straightforward - the printer you are testing hasn't implemented all the required attributes or operations. Why it catastrophically failed to produce a proper .plist file needs investigation, but for now Canon can just work towards implementing all those missing attributes and operations.

The problems with document testing are more profound - our IPP Everywhere Self-Certification suite doesn't accommodate printers that don't support either US Letter or A4. But I think it should. The question is how. I would suggest raising this issue on the ipp@pwg.org reflector so that the PWG IPP Workgroup can identify a proper path forward.

**Comment by michaelrsweet** [comment]
[master e1e5a64] Rework all PWG raster tests to use the new GENERATE-FILE directive.  No more downloading of PWG raster files! (Issue #78)
