### ISSUE TITLE
ippevesubmit: insert dates for plist files, not date when tool was run

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#81]
The ippevesubmit tool generates JSON that includes a "date" field whose value is the date the tool was run, not the file date of the .plist files. This is a problem because If you run the IPP Everywhere Self-Certification tools and certify a printer on August 15, 2020 but run ippevesubmit on November 1, 2021, and there was a cutoff date in September, the user will be unable to have their submissions be accepted.

**Comment by michaelrsweet** [comment]
[master 1860a59] Use the modification date of the PLIST files for the submission date (Issue #81)
