### ISSUE TITLE
Build on macOS arm64 builds arm64e which doesn't work

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#82]
@michaelrsweet said the configure scripts are building on macOS Apple Silicon targeting arm64e (which was from the old developer transition kit devices not released to the public) rather than arm64.

Update the configure script to target arm64 instead of arm64e.

**Comment by michaelrsweet** [comment]
[master 6b689d0] Fix Mac ARM builds (Issue #82)
