### ISSUE TITLE
Set the "job-name" attribute using the test name

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#85]
When searching a PCAP file, it would be very useful if there were some artifact in a Job that would indicate the test being run. Currently the "job-name" attribute set in a Print-Job operation doesn't have the test name. An example is here in the current revision of tests/document-tests.test D-1.4:

https://github.com/istopwg/ippeveselfcert/blob/70ebcab3f1fc2e61bed5aa958e095fdc82a48b17/tests/document-tests.test#L478

Update the test files to supply a "job-name" that has the test name in it.

**Comment by michaelrsweet** [comment]
[master 9e5a73b] Add test numbers to all print job tests (Issue #85)
