### ISSUE TITLE
document-tests.sh: provide "ipptool" with "-T 120" option to increase the timeout time

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#91]
Some implementations are slow to respond. Until Issue #90 is resolved, increase the timeout time for ipptool by adding the "-T 120" option in the shell scripts and batch files where ipptool is used.

**Comment by michaelrsweet** [comment]
@wifiprintguy do you think this needs to be in update 4?

**Comment by wifiprintguy** [comment]
It would help if it was in Update 4. I am sorry for the thrash. 

I wondered if, as a solution to this problem, the shell scripts / batch files themselves might take additional options beyond the name of the printer and pass those onto ipptool, but if we haven't needed that thus far, then that would be overkill.

**Comment by michaelrsweet** [comment]
[master db868dd] Bump version and add 120 second timeout (Issue #91)
