### ISSUE TITLE
document-tests.sh: provide "ipptool" with "-T 240" option to increase the timeout time

### ISSUE THREAD

**Issue by wifiprintguy** [istopwg/ippeveselfcert#92]
HP Inc. once again is requesting that the timeout for operations be changed to 240 seconds to allow some of our printers with poor Print-Job operation implementations to be certified. This is basically re-opening Issue #91 but I'm filing it as a separate request.

If Issue #90 were implemented instead, this issue would also be resolved, since almost all real clients use Create-Job / Send-Document rather than Print-Job and the timeout issue in these printers is only with Print-Job.

**Comment by michaelrsweet** [comment]
[master 9740a0a] Update timeout to 300 seconds (Issue #92)
