### ISSUE TITLE
IPP Everywhere Printer Self-Certification Results

### ISSUE THREAD

**Issue by jacobsb** [istopwg/ippeveselfcert#97]
Please see attached 2 results for self certification:
[Lexmark MX632adwe.json.zip](https://github.com/istopwg/ippeveselfcert/files/11323022/Lexmark.MX632adwe.json.zip)
[Lexmark CX635adwe.json.zip](https://github.com/istopwg/ippeveselfcert/files/11323024/Lexmark.CX635adwe.json.zip)

**Comment by michaelrsweet** [comment]
Thanks, looking at these JSON files it looks like you might have used an old ippevesubmit to generate them? Still complains about the mismatch in the number of tests so you had to use the `--override` option:

```
/* Note: submitted with --override */
/* IPP errors:
Wrong number of tests (got 51, expected 41).
*/
/* Document errors:
Wrong number of tests (got 65, expected 53).
*/
```

**Comment by jacobsb** [comment]
> Thanks, looking at these JSON files it looks like you might have used an old ippevesubmit to generate them? Still complains about the mismatch in the number of tests so you had to use the `--override` option:
> 
> ```
> /* Note: submitted with --override */
> /* IPP errors:
> Wrong number of tests (got 51, expected 41).
> */
> /* Document errors:
> Wrong number of tests (got 65, expected 53).
> */
> ```

Yes, there is a significant delay between when we run the tests internally and submit the results to the PWG.  What we typically do is run and pass the tests while the product is nearing the end of the development phase but we cannot submit the results until the products are publicly announced by our company.

**Comment by michaelrsweet** [comment]
OK, thanks for the explanation.
